import { error } from '@sveltejs/kit';
import packages from '$lib/data/packages.json';
import type { EntryGenerator, PageLoad } from './$types';

// The site prerenders, so every package needs naming up front. The data is
// generated by script/packages.mjs, which is also what keeps the rule listings
// from drifting: they come out of the packages themselves.
export const entries: EntryGenerator = () => packages.map((p) => ({ name: p.name }));

export const load: PageLoad = ({ params }) => {
	const pkg = packages.find((p) => p.name.toLowerCase() === params.name.toLowerCase());
	if (!pkg) {
		error(404, `No package named "${params.name}".`);
	}
	return { pkg };
};
